### ISSUE TITLE
Need feedback that login is processing

### ISSUE THREAD

**Issue by jimboca** [Einstein42/udi-polyglotv2#2]
Running on my RPi 1 B+ it takes a while to process the login credentials, and while that is happening the UI doesn't show that it's waiting for the authorization to complete.

**Comment by Einstein42** [comment]
Wow, I never got these notifications. That's odd. Anyway. I need to relax the crypto a bit, I went overboard I think. No problem, I'll work on this.

**Comment by jimboca** [comment]
haha, I was wo why you never responded!

**Comment by Einstein42** [comment]
I have changed the salt down to 2 passes. This should be resolved now. Reopen if necessary.
