### ISSUE TITLE
Unable to start, fresh install

### ISSUE THREAD

**Issue by exking** [Einstein42/udi-polyglotv2#2]
There is what I see. It looks like it's trying to enumerate node servers on ISY, but it does not know the ISY username/password just yet since it never given me an opportunity to enter!

12/12/2017, 8:32:00 AM - info: Starting Polyglot version 2.0
12/12/2017, 8:32:01 AM - info: MongoDB: Connected
12/12/2017, 8:32:01 AM - info: Settings: Polyglot Version 2.0.26
12/12/2017, 8:32:01 AM - info: Settings: Retrieved config from database
12/12/2017, 8:32:01 AM - info: Settings: Retrieved config overrides from .env and updated database
12/12/2017, 8:32:01 AM - info: SSL: No HTTPS Certificate or Key found. Generating...
12/12/2017, 8:32:40 AM - info: SSL: Certificate Generation completed successfully.
12/12/2017, 8:32:40 AM - debug: ISY: 401 - http://10.0.1.27:80/rest/config/
12/12/2017, 8:32:40 AM - error: ISY: Failed to get version.
12/12/2017, 8:32:40 AM - info: Mosca MQTT Broker Service: Started
12/12/2017, 8:32:41 AM - info: MQTT Client Service: Started
12/12/2017, 8:32:41 AM - info: HTTP Interface Service: Started - Port: 3000
12/12/2017, 8:32:41 AM - debug: MongoDB: 0 NodeServer(s) retrieved from database
12/12/2017, 8:32:41 AM - error: uncaughtException: callback is not defined date=Tue Dec 12 2017 08:32:41 GMT-0600 (CST), pid=14164, uid=998, gid=995, cwd=/home/poly/polyglot, execPath=/home/poly/polyglot/polyglot-v2-linux-armv7, version=v6.10.3, argv=[/home/poly/polyglot/polyglot-v2-linux-armv7, /snapshot/udi-polyglotv2/bin/polyglot-v2.js], rss=109084672, heapTotal=85819392, heapUsed=73404496, external=37732553, loadavg=[1.6904296875, 1.3095703125, 1.17236328125], uptime=90606
ReferenceError: callback is not defined
    at Function.verifyNonManagedNodeServers (/snapshot/udi-polyglotv2/lib/models/nodeserver.js:712:47)
    at NodeServerSchema.statics.loadNodeServers.NodeServerModel.getAllNodeServers (/snapshot/udi-polyglotv2/lib/models/nodeserver.js:657:20)
    at Query.Model.$wrapCallback (/snapshot/udi-polyglotv2/node_modules/mongoose/lib/model.js:3932:16)
    at /snapshot/udi-polyglotv2/node_modules/kareem/index.js:273:21
    at /snapshot/udi-polyglotv2/node_modules/kareem/index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
12/12/2017, 8:32:41 AM - info: Polyglot shutdown complete with code: 1

**Comment by Einstein42** [comment]
I found this issue as well. This is fixed with the binary currently uploaded.
