### ISSUE TITLE
ERROR    parseInput: '7651582'

### ISSUE THREAD

**Issue by jimboca** [Einstein42/udi-polyglotv2#7]
I don't know what happened, my discover was working, then it started saying:
```
2018-1-1 15:20:39 - debug: REST: DISCOVER Command received from ISY for n002_7651582
2018-1-1 15:20:39 - debug: Sending DISCOVER to n002_7651582
```
which looks correct, but the nodeserver log says:
```
2018-01-01 15:19:33,997 ERROR    parseInput: '7651582'
```
Seemed to be chopping off the 'DISCOVER n001_' part?

I don't know how I got in that state, but the error was not from my code.  I tried restarting my node server, and restarting polyglot-v2 but still got the error.

I deleted the nodeserver in the web ui, then rebooted, reinstalled nodeserver, rebooted, and now the discovery works fine?

**Comment by jimboca** [comment]
I created a local variable st in one of the Controller methods... That probably broke it?

**Comment by jimboca** [comment]
Nope, that wasn't it... I'm in that state again :(

**Comment by jimboca** [comment]
Einstein42 said:
It’s basically throwing a KeyError on parsing the JSON it’s receiving for that command, that’s the exception it is catching for that error
It’s saying that self.nodes doesn’t contain the address
Line 502 in polyinterface.py change from: LOGGER.error(‘parseInput: {}’.format(e)) to LOGGER.error(‘parseInput: {} on {}’.format(e, input))

**Comment by Einstein42** [comment]
This should be resolved. Re-open if it happens again.
